config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
		scope module: :medical_device do 
				resources :medical_devices
			end  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/medical_device.rb
module MedicalDevice
  def self.table_name_prefix
    'medical_device_'
  end
  
  def self.sync_device_instances
    Apiotics.sync_device_instances(self.name)
  end
  
  def self.sync_devices
    Apiotics.sync_device_instances(self.name, true)
  end
    
end

app/models/medical_device/buzzer.rb
module MedicalDevice
  class Buzzer < ApplicationRecord
    # The method(s) that correspond to device interfaces are: buzzer port_number 
    
    belongs_to :medical_device
    attr_accessor :skip_extract
    after_commit :extract, unless: :skip_extract
    after_commit :channel_push
    
		validates :port_number, inclusion: { in: %w(J5 J6 J7 J8 J9 J10 J11),
   	message: "%{value} is not a valid port_number" }
		
    
    def sync
      Apiotics.sync(self)
    end
    
    private
  
    def extract
      begin
        Apiotics::Extract.send(self)
      rescue => e
        puts e
      end
    end
    
    def channel_push
      if Apiotics.configuration.push == true
        interfaces = Hash.new
        puts self.previous_changes
        self.previous_changes.each do |k,v|
          if Apiotics::Extract.is_target(self, k)
            interfaces[k] = v[1].to_s
          end
        end
        interfaces.each do |k,v|
          ActionCable.server.broadcast "#{self.class.parent.to_s.underscore.downcase.gsub(" ", "_")}_channel",
            apiotics_instance: self.medical_device.apiotics_instance,
            worker_name: self.class.parent.to_s.underscore.downcase.gsub(" ", "_"),
            model_name: self.class.name.demodulize.to_s.underscore.downcase.gsub(" ", "_"),
            interface: k,
            value: v
        end
      end
    end
  
  end
end

app/models/medical_device/four_digit_display.rb
module MedicalDevice
  class FourDigitDisplay < ApplicationRecord
    # The method(s) that correspond to device interfaces are: clock display port_number 
    
    belongs_to :medical_device
    attr_accessor :skip_extract
    after_commit :extract, unless: :skip_extract
    after_commit :channel_push
    
		validates :port_number, inclusion: { in: %w(J5 J6 J7 J8 J9 J10),
   	message: "%{value} is not a valid port_number" }
		
    
    def sync
      Apiotics.sync(self)
    end
    
    private
  
    def extract
      begin
        Apiotics::Extract.send(self)
      rescue => e
        puts e
      end
    end
    
    def channel_push
      if Apiotics.configuration.push == true
        interfaces = Hash.new
        puts self.previous_changes
        self.previous_changes.each do |k,v|
          if Apiotics::Extract.is_target(self, k)
            interfaces[k] = v[1].to_s
          end
        end
        interfaces.each do |k,v|
          ActionCable.server.broadcast "#{self.class.parent.to_s.underscore.downcase.gsub(" ", "_")}_channel",
            apiotics_instance: self.medical_device.apiotics_instance,
            worker_name: self.class.parent.to_s.underscore.downcase.gsub(" ", "_"),
            model_name: self.class.name.demodulize.to_s.underscore.downcase.gsub(" ", "_"),
            interface: k,
            value: v
        end
      end
    end
  
  end
end

app/models/medical_device/galvanic_skin_response_sensor.rb
module MedicalDevice
  class GalvanicSkinResponseSensor < ApplicationRecord
    # The method(s) that correspond to device interfaces are: data port_number 
    
    belongs_to :medical_device
    attr_accessor :skip_extract
    after_commit :extract, unless: :skip_extract
    after_commit :channel_push
    after_update :change_display

   	validates :data, inclusion: { in: 0..4095,
   	message: "%{value} is not within the range 0..4095" }
		
		validates :port_number, inclusion: { in: %w(J5 J6 J7 J8 J9 J10),
   	message: "%{value} is not a valid port_number" }
		
    
    def sync
      Apiotics.sync(self)
    end
    
    private
  
    def extract
      begin
        Apiotics::Extract.send(self)
      rescue => e
        puts e
      end
    end
    
    def channel_push
      if Apiotics.configuration.push == true
        interfaces = Hash.new
        puts self.previous_changes
        self.previous_changes.each do |k,v|
          if Apiotics::Extract.is_target(self, k)
            interfaces[k] = v[1].to_s
          end
        end
        interfaces.each do |k,v|
          ActionCable.server.broadcast "#{self.class.parent.to_s.underscore.downcase.gsub(" ", "_")}_channel",
            apiotics_instance: self.medical_device.apiotics_instance,
            worker_name: self.class.parent.to_s.underscore.downcase.gsub(" ", "_"),
            model_name: self.class.name.demodulize.to_s.underscore.downcase.gsub(" ", "_"),
            interface: k,
            value: v
        end
      end
     end

     def change_display
      if self.medical_device.name == #insert device name here in quotes 
        self.medical_device.four_digit_display.display = self.data.to_s
        self.medical_device.four_digit_display.save
      end
    end
  end
end

app/models/medical_device/heart_rate_sensor.rb
module MedicalDevice
  class HeartRateSensor < ApplicationRecord
    # The method(s) that correspond to device interfaces are: data port_number 
    
    belongs_to :medical_device
    attr_accessor :skip_extract
    after_commit :extract, unless: :skip_extract
    after_commit :channel_push
    
		validates :port_number, inclusion: { in: %w(J5 J6 J7 J8 J9 J10 J11),
   	message: "%{value} is not a valid port_number" }
		
    
    def sync
      Apiotics.sync(self)
    end
    
    private
  
    def extract
      begin
        Apiotics::Extract.send(self)
      rescue => e
        puts e
      end
    end
    
    def channel_push
      if Apiotics.configuration.push == true
        interfaces = Hash.new
        puts self.previous_changes
        self.previous_changes.each do |k,v|
          if Apiotics::Extract.is_target(self, k)
            interfaces[k] = v[1].to_s
          end
        end
        interfaces.each do |k,v|
          ActionCable.server.broadcast "#{self.class.parent.to_s.underscore.downcase.gsub(" ", "_")}_channel",
            apiotics_instance: self.medical_device.apiotics_instance,
            worker_name: self.class.parent.to_s.underscore.downcase.gsub(" ", "_"),
            model_name: self.class.name.demodulize.to_s.underscore.downcase.gsub(" ", "_"),
            interface: k,
            value: v
        end
      end
    end
  
  end
end

app/models/medical_device/medical_device.rb
module MedicalDevice
  class MedicalDevice < ApplicationRecord
    
      
        
          has_one :buzzer, dependent: :destroy
          accepts_nested_attributes_for :buzzer
        
          has_one :heart_rate_sensor, dependent: :destroy
          accepts_nested_attributes_for :heart_rate_sensor
        
          has_one :galvanic_skin_response_sensor, dependent: :destroy
          accepts_nested_attributes_for :galvanic_skin_response_sensor
        
          has_one :four_digit_display, dependent: :destroy
          accepts_nested_attributes_for :four_digit_display
        
      
    
  end
end

app/controllers/medical_device/medical_devices_controller.rb
module MedicalDevice
  class MedicalDevicesController < ApplicationController
    before_action :set_medical_device, only: [:show, :edit, :update, :destroy]

    # GET /alert/leds
    def index
      @medical_devices = ::MedicalDevice::MedicalDevice.all
    end

    # GET /alert/leds/1
    def show
    end

    # GET /alert/leds/new
    def new
      redirect_to medical_devices_url, notice: 'You are not authorized to do that.'
    end

    # GET /alert/leds/1/edit
    def edit
    end

    # POST /alert/leds
    def create
      @medical_device = ::MedicalDevice::MedicalDevice.new(medical_device_params)

      if @medical_device.save
        redirect_to medical_device_path(@medical_device), notice: 'MedicalDevice was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /alert/leds/1
    def update
      if @medical_device.update(medical_device_params)
        redirect_to medical_device_path(@medical_device), notice: 'MedicalDevice was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /alert/leds/1
    def destroy
      @medical_device.destroy
      redirect_to medical_devices_url, notice: 'medical_device was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_medical_device
        @medical_device = ::MedicalDevice::MedicalDevice.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def medical_device_params
        params.fetch(:medical_device_medical_device, {}).permit(:id, :apiotics_instance, :buzzer_attributes => ["buzzer", "port_number", "id"], :heart_rate_sensor_attributes => ["data", "port_number", "id"], :galvanic_skin_response_sensor_attributes => ["data", "port_number", "id"], :four_digit_display_attributes => ["clock", "display", "port_number", "id"])
      end
  end
end

app/views/medical_device/medical_devices/_form.html.erb
<%= simple_form_for(@medical_device, url: medical_device_path(@medical_device)) do |form| %>
  <table>
    <tr>
      <th>
        Id
      </th>
      <td>
        <%= @medical_device.apiotics_instance %>
      </td>
    </tr>
    <tr>
      <th>
        Name
      </th>
      <td>
          <%= @medical_device.name %>
      </td>
    </tr>
    
      <tr>
        <th>
          Buzzer
        </th>
        <%= form.simple_fields_for :buzzer do |fields| %>
					 <td>
          	
							
							
								<%= fields.input :buzzer %>
							
          	
							
							
	              	<%= fields.input :port_number, collection: ["J5", "J6", "J7", "J8", "J9", "J10", "J11"] %>
							
          	
					</td>
        <% end %>
      </tr>
    
      <tr>
        <th>
          HeartRateSensor
        </th>
        <%= form.simple_fields_for :heart_rate_sensor do |fields| %>
					 <td>
          	
							
							
								<%= fields.input :data %>
							
          	
							
							
	              	<%= fields.input :port_number, collection: ["J5", "J6", "J7", "J8", "J9", "J10", "J11"] %>
							
          	
					</td>
        <% end %>
      </tr>
    
      <tr>
        <th>
          GalvanicSkinResponseSensor
        </th>
        <%= form.simple_fields_for :galvanic_skin_response_sensor do |fields| %>
					 <td>
          	
							
							
								<%= fields.input :data %>
							
          	
							
							
	              	<%= fields.input :port_number, collection: ["J5", "J6", "J7", "J8", "J9", "J10"] %>
							
          	
					</td>
        <% end %>
      </tr>
    
      <tr>
        <th>
          FourDigitDisplay
        </th>
        <%= form.simple_fields_for :four_digit_display do |fields| %>
					 <td>
          	
							
							
								<%= fields.input :clock %>
							
          	
							
							
								<%= fields.input :display %>
							
          	
							
							
	              	<%= fields.input :port_number, collection: ["J5", "J6", "J7", "J8", "J9", "J10"] %>
							
          	
					</td>
        <% end %>
      </tr>
    
      <tr>
        <th>
          &nbsp;
        </th>
        <td>
          <div class="actions">
            <%= form.submit %>
          </div>
        </td>
      </tr>
  </table>
<% end %>

app/views/medical_device/medical_devices/edit.html.erb
<h1>Editing MedicalDevice</h1>

<%= render 'form' %>

<%= link_to 'Show', medical_device_path(@medical_device) %> |
<%= link_to 'Back', medical_devices_path %>

app/views/medical_device/medical_devices/index.html.erb
<p id="notice"><%= notice %></p>
<h1>
  MedicalDevices
</h1>

<table>
  <thead>
    <tr>
      <th style="border: 1px solid black;">
        Id
      </th>
      <th style="border: 1px solid black;">
        Name
      </th>
      
        <th colspan='2' style="border: 1px solid black;">
          Buzzer
        </th>
      
        <th colspan='2' style="border: 1px solid black;">
          HeartRateSensor
        </th>
      
        <th colspan='2' style="border: 1px solid black;">
          GalvanicSkinResponseSensor
        </th>
      
        <th colspan='3' style="border: 1px solid black;">
          FourDigitDisplay
        </th>
      
      <th style="border: 1px solid black;">
        &nbsp;
      </th>
    </tr>
    <tr>
      <th>
        &nbsp;
      </th>
      <th>
        &nbsp;
      </th>
      
        
          <th>
            buzzer
          </th>
        
          <th>
            port_number
          </th>
        
      
        
          <th>
            data
          </th>
        
          <th>
            port_number
          </th>
        
      
        
          <th>
            data
          </th>
        
          <th>
            port_number
          </th>
        
      
        
          <th>
            clock
          </th>
        
          <th>
            display
          </th>
        
          <th>
            port_number
          </th>
        
      
      <th>
        &nbsp;
      </th>
    </tr>
  </thead>
  <tbody>
    <% @medical_devices.each do |object| %>
      <tr id='<%= object.apiotics_instance %>'>
        <td>
          <%= object.apiotics_instance %>
        </td>
        <td>
          <%= object.name %>
        </td>
        
          
            <td class='medical_device-buzzer-buzzer'>
              <%= object.buzzer.buzzer %>
            </td>
          
            <td class='medical_device-buzzer-port_number'>
              <%= object.buzzer.port_number %>
            </td>
          
        
          
            <td class='medical_device-heart_rate_sensor-data'>
              <%= object.heart_rate_sensor.data %>
            </td>
          
            <td class='medical_device-heart_rate_sensor-port_number'>
              <%= object.heart_rate_sensor.port_number %>
            </td>
          
        
          
            <td class='medical_device-galvanic_skin_response_sensor-data'>
              <%= object.galvanic_skin_response_sensor.data %>
            </td>
          
            <td class='medical_device-galvanic_skin_response_sensor-port_number'>
              <%= object.galvanic_skin_response_sensor.port_number %>
            </td>
          
        
          
            <td class='medical_device-four_digit_display-clock'>
              <%= object.four_digit_display.clock %>
            </td>
          
            <td class='medical_device-four_digit_display-display'>
              <%= object.four_digit_display.display %>
            </td>
          
            <td class='medical_device-four_digit_display-port_number'>
              <%= object.four_digit_display.port_number %>
            </td>
          
        
        <td>
          <%= link_to "Edit", edit_medical_device_path(object)%>
          <%= link_to "Show", medical_device_path(object) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/medical_device/medical_devices/show.html.erb
<p id="notice"><%= notice %></p>
<h1>
  MedicalDevice
</h1>
<table>
  <thead>
    <tr>
      <th style="border: 1px solid black;">
        Id
      </th>
      <th style="border: 1px solid black;">
        Name
      </th>
      
        <th colspan='2' style="border: 1px solid black;">
          Buzzer
        </th>
      
        <th colspan='2' style="border: 1px solid black;">
          HeartRateSensor
        </th>
      
        <th colspan='2' style="border: 1px solid black;">
          GalvanicSkinResponseSensor
        </th>
      
        <th colspan='3' style="border: 1px solid black;">
          FourDigitDisplay
        </th>
      
    </tr>
    <tr>
      <th>
        &nbsp;
      </th>
      <th>
        &nbsp;
      </th>
      
        
          <th>
            buzzer
          </th>
        
          <th>
            port_number
          </th>
        
      
        
          <th>
            data
          </th>
        
          <th>
            port_number
          </th>
        
      
        
          <th>
            data
          </th>
        
          <th>
            port_number
          </th>
        
      
        
          <th>
            clock
          </th>
        
          <th>
            display
          </th>
        
          <th>
            port_number
          </th>
        
      
    </tr>
  </thead>
  <tbody>
    <tr id='<%= @medical_device.apiotics_instance %>'>
      <td>
        <%= @medical_device.apiotics_instance %>
      </td>
      <td>
        <%= @medical_device.name %>
      </td>
      
        
          <td class='medical_device-buzzer-buzzer'>
            <%= @medical_device.buzzer.buzzer %>
          </td>
        
          <td class='medical_device-buzzer-port_number'>
            <%= @medical_device.buzzer.port_number %>
          </td>
        
      
        
          <td class='medical_device-heart_rate_sensor-data'>
            <%= @medical_device.heart_rate_sensor.data %>
          </td>
        
          <td class='medical_device-heart_rate_sensor-port_number'>
            <%= @medical_device.heart_rate_sensor.port_number %>
          </td>
        
      
        
          <td class='medical_device-galvanic_skin_response_sensor-data'>
            <%= @medical_device.galvanic_skin_response_sensor.data %>
          </td>
        
          <td class='medical_device-galvanic_skin_response_sensor-port_number'>
            <%= @medical_device.galvanic_skin_response_sensor.port_number %>
          </td>
        
      
        
          <td class='medical_device-four_digit_display-clock'>
            <%= @medical_device.four_digit_display.clock %>
          </td>
        
          <td class='medical_device-four_digit_display-display'>
            <%= @medical_device.four_digit_display.display %>
          </td>
        
          <td class='medical_device-four_digit_display-port_number'>
            <%= @medical_device.four_digit_display.port_number %>
          </td>
        
      
    </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_medical_device_path(@medical_device) %> |
<%= link_to 'Back', medical_devices_path %>